# Generated by Django 3.2.4 on 2021-08-05 01:38

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=Registration.models.user_dir_img1),
        ),
    ]
