# Generated by Django 3.2.6 on 2021-08-08 01:55

import Registration.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_userimage_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='image1',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/profile_pic_dir', location='static/profile_pic_dir'), upload_to=Registration.models.user_dir_profile_pic),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=Registration.models.user_dir_img2),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=Registration.models.user_dir_img3),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=Registration.models.user_dir_img4),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=Registration.models.user_dir_img5),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=Registration.models.user_dir_img6),
        ),
    ]
