# Generated by Django 3.2.6 on 2021-08-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20210808_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='gender',
            field=models.CharField(choices=[('pcs', 'Male.'), ('set', 'Female')], max_length=6, null=True),
        ),
    ]
