# Generated by Django 3.2.6 on 2021-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_alter_userstudent_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='guardian_cp_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='guardian_fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
