# Generated by Django 3.2.6 on 2021-08-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_auto_20210820_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='block',
            field=models.CharField(choices=[('Block-A', 'Block-A'), ('Block-B', 'Block-B'), ('Block-C', 'Block-C'), ('Block-D', 'Block-D')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='course',
            field=models.CharField(choices=[('BSCS', 'BSCS')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=3, null=True),
        ),
    ]
