# Generated by Django 3.2.6 on 2021-09-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20210908_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbookexit',
            old_name='date_time_in',
            new_name='date_time_exit',
        ),
    ]
