# Generated by Django 3.2.6 on 2021-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_rename_date_time_in_logbookexit_date_time_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('block', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('body_temp', models.CharField(max_length=100, null=True)),
                ('date_time_in', models.DateTimeField(null=True)),
                ('date_time_exit', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LogbookEntrance',
        ),
        migrations.DeleteModel(
            name='LogbookExit',
        ),
    ]
