# Generated by Django 3.2.6 on 2021-09-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_auto_20210910_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='cp_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
