# Generated by Django 3.2.6 on 2021-09-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_logbook_cp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='body_temp_second_attempt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
